### ISSUE TITLE
Cannot speak - red box

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/tfwm-blind-and-disabled-pass#75]
Comment from Warren:

I have selected I cannot speak category and presented with a red box saying you cannot apply. Indicates I have failed the application. In other locations there is a green box followed by a red box. A red box just on its own makes me think I have failed a check or something. 

![Screenshot 2022-10-19 at 12 04 59](https://user-images.githubusercontent.com/68856858/196674285-7bff4743-e370-4733-9d44-893a19e06cbb.png)

**Comment by sam-wmca** [comment]
Considering this context I think we can change it to warning text instead of the green/red format.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/66072673/196679928-acba58f9-e130-4229-b6c7-7f7fafed7379.png">

**Comment by Doodlepaul** [comment]
@mushtaque12  Can you add the 'You cannot apply...' text. Currently starts at 'If...' and doesn't make sense
