### ISSUE TITLE
Photo information

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/tfwm-blind-and-disabled-pass#76]
Warren has requested the functionality to crop/reposition a photo.

Whilst I'm not suggesting we do this, is it worth adding more information - thinking of the OPP info so that people don't need to crop or reposition...

![Screenshot 2022-10-19 at 12 12 43](https://user-images.githubusercontent.com/68856858/196675825-572f3026-d501-4c94-b95e-a74f9cd7b951.png)

**Comment by sam-wmca** [comment]
Yes I think so! Matches the [GDS pattern for concessionary passes](https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/photo/design) if we give clear direction too.

**Comment by Doodlepaul** [comment]
@mushtaque12 Can we revise the image information to include the above, so that it matches the section on the OPP.
